language: node_js
node_js:
  - 'lts/*'
sudo: false
addons:
  firefox: latest
notifications:
  email: false
install:
  - npm install
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
