language: python
python: 3.6
sudo: false
addons:
  firefox: latest
notifications:
  email: false
before_install:
  - nvm install 10
install:
  - pip install jupyterlab==0.35.*
  - npm install
  - npm run build
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
